"use client";

import { useState } from "react";
import { generateBalancedTeams } from "@/lib/team-generator";

interface Player {
  id: string;
  full_name: string;
  primary_position: string;
  skill_level: number | null;
}

interface TeamGeneratorProps {
  players: Player[];
}

export default function TeamGenerator({
  players,
}: TeamGeneratorProps) {
  const [teamA, setTeamA] = useState<Player[]>([]);
  const [teamB, setTeamB] = useState<Player[]>([]);

  function generateTeams() {
    const result = generateBalancedTeams(players);

    setTeamA(result.teamA);
    setTeamB(result.teamB);

    console.log(result);
  }

  function getPositionIcon(position: string) {
  switch (position.toLowerCase()) {
    case "goalkeeper":
      return "🥅";
    case "defender":
      return "🛡️";
    case "midfielder":
      return "⚙️";
    case "forward":
      return "⚡";
    default:
      return "👤";
  }
}

function getSkillStars(skill: number | null) {
  return "⭐".repeat(skill ?? 3);
}

function copyTeams() {
  let text = "";

  text += "⚽ WEEKLY FOOTY ⚽\n";
  text += "━━━━━━━━━━━━━━━━━━━━━━\n\n";

  text += "🟢 TEAM A\n\n";

  teamA.forEach((player) => {
    text += `${getPositionIcon(player.primary_position)} ${player.full_name}\n`;
    text += `${getSkillStars(player.skill_level)}\n\n`;
  });

  text += "━━━━━━━━━━━━━━━━━━━━━━\n\n";

  text += "🔵 TEAM B\n\n";

  teamB.forEach((player) => {
    text += `${getPositionIcon(player.primary_position)} ${player.full_name}\n`;
    text += `${getSkillStars(player.skill_level)}\n\n`;
  });

  text += "━━━━━━━━━━━━━━━━━━━━━━\n";
  text += "Generated by Weekly Footy ⚽";

  navigator.clipboard.writeText(text);

  alert("✅ Teams copied to clipboard!");
}
  return (
    <div className="mt-8 rounded-3xl border border-zinc-800 bg-[#111111] p-8">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-black uppercase">
          Team Generator
        </h2>

        <div className="flex gap-3">
          <button
            onClick={copyTeams}
            disabled={teamA.length === 0}
            className="rounded-xl border border-zinc-700 px-5 py-3 font-black uppercase hover:border-[#ccff00] disabled:opacity-40"
          >
            📋 Copy Teams
          </button>

          <button
            onClick={generateTeams}
            className="rounded-xl bg-[#ccff00] px-5 py-3 font-black uppercase text-black hover:bg-[#b8eb00] transition"
          >
            🎲 Generate Teams
          </button>
        </div>
      </div>

      {teamA.length > 0 && (
        <div className="mt-8 grid gap-8 md:grid-cols-2">
          {/* Team A */}
          <div>
            <h3 className="mb-4 text-xl font-black text-[#ccff00]">
              🟢 Team A
            </h3>

            <div className="space-y-3">
              {teamA.map((player) => (
                <div
                  key={player.id}
                  className="rounded-xl border border-zinc-800 p-4"
                >
                  <p className="font-bold text-lg">
                    {player.full_name}
                  </p>

                  <p className="text-sm uppercase text-zinc-500">
                    {player.primary_position}
                  </p>

                  <p className="mt-1 text-xs text-[#ccff00]">
                    ⭐ Skill: {player.skill_level ?? 3}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Team B */}
          <div>
            <h3 className="mb-4 text-xl font-black text-[#4da6ff]">
              🔵 Team B
            </h3>

            <div className="space-y-3">
              {teamB.map((player) => (
                <div
                  key={player.id}
                  className="rounded-xl border border-zinc-800 p-4"
                >
                  <p className="font-bold text-lg">
                    {player.full_name}
                  </p>

                  <p className="text-sm uppercase text-zinc-500">
                    {player.primary_position}
                  </p>

                  <p className="mt-1 text-xs text-[#4da6ff]">
                    ⭐ Skill: {player.skill_level ?? 3}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}